"""init schema mvp

Revision ID: 903f737d4420
Revises: 
Create Date: 2026-10-04 20:56:29.080095

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '903f737d4420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kata_sandi_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('PEMILIK', 'PEKERJA', name='peranuser'), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'NONAKTIF', 'WAJIB_GANTI_SANDI', name='statususer'), nullable=False),
    sa.Column('dibuat_pada', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('aksi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entitas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entitas_id', sa.Uuid(), nullable=False),
    sa.Column('nilai_lama', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nilai_baru', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('catatan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('waktu', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('bahan_pakan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pemilik_id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.Column('status_sistem', sa.Enum('DI_DALAM_SISTEM', 'DI_LUAR_SISTEM', name='statusbahan'), nullable=False),
    sa.Column('batas_maksimum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pemilik_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bahan_pakan_pemilik_id'), 'bahan_pakan', ['pemilik_id'], unique=False)
    op.create_table('jenis_ayam',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pemilik_id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pemilik_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jenis_ayam_pemilik_id'), 'jenis_ayam', ['pemilik_id'], unique=False)
    op.create_table('kandang',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pemilik_id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lokasi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('AKTIF', 'NONAKTIF', name='statuskandang'), nullable=False),
    sa.ForeignKeyConstraint(['pemilik_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kandang_pemilik_id'), 'kandang', ['pemilik_id'], unique=False)
    op.create_table('notifikasi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jenis', sa.Enum('PERINTAH_SUKSES', 'PERINTAH_GAGAL', 'ALAT_OFFLINE', 'ALAT_ERROR', 'STOK_MENIPIS', 'STOK_KOSONG', 'PERLU_DITINJAU', name='jenisnotifikasi'), nullable=False),
    sa.Column('judul', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pesan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('BELUM_DIBACA', 'SUDAH_DIBACA', name='statusnotifikasi'), nullable=False),
    sa.Column('dibuat_pada', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifikasi_user_id'), 'notifikasi', ['user_id'], unique=False)
    op.create_table('nutrisi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pemilik_id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('satuan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipe_batas', sa.Enum('MINIMUM', 'MAKSIMUM', 'MIN_MAKS', name='tipebatas'), nullable=False),
    sa.ForeignKeyConstraint(['pemilik_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrisi_pemilik_id'), 'nutrisi', ['pemilik_id'], unique=False)
    op.create_table('alat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kandang_id', sa.Uuid(), nullable=False),
    sa.Column('device_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'ERROR', name='statusalat'), nullable=False),
    sa.Column('versi_jadwal_aktif', sa.Integer(), nullable=True),
    sa.Column('waktu_terakhir_sinkron', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kandang_id'], ['kandang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alat_device_token'), 'alat', ['device_token'], unique=True)
    op.create_index(op.f('ix_alat_kandang_id'), 'alat', ['kandang_id'], unique=True)
    op.create_table('fase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jenis_ayam_id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('umur_min_hari', sa.Integer(), nullable=False),
    sa.Column('umur_max_hari', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jenis_ayam_id'], ['jenis_ayam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fase_jenis_ayam_id'), 'fase', ['jenis_ayam_id'], unique=False)
    op.create_table('kandungan_nutrisi_bahan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bahan_pakan_id', sa.Uuid(), nullable=False),
    sa.Column('nutrisi_id', sa.Uuid(), nullable=False),
    sa.Column('nilai_per_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bahan_pakan_id'], ['bahan_pakan.id'], ),
    sa.ForeignKeyConstraint(['nutrisi_id'], ['nutrisi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='unique(bahan_pakan_id, nutrisi_id) ditegakkan di migrasi'
    )
    op.create_index(op.f('ix_kandungan_nutrisi_bahan_bahan_pakan_id'), 'kandungan_nutrisi_bahan', ['bahan_pakan_id'], unique=False)
    op.create_index(op.f('ix_kandungan_nutrisi_bahan_nutrisi_id'), 'kandungan_nutrisi_bahan', ['nutrisi_id'], unique=False)
    op.create_table('penugasan_kandang',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kandang_id', sa.Uuid(), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'BERAKHIR', name='statuspenugasan'), nullable=False),
    sa.ForeignKeyConstraint(['kandang_id'], ['kandang.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penugasan_kandang_kandang_id'), 'penugasan_kandang', ['kandang_id'], unique=False)
    op.create_index(op.f('ix_penugasan_kandang_user_id'), 'penugasan_kandang', ['user_id'], unique=False)
    op.create_table('kebutuhan_nutrisi_fase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fase_id', sa.Uuid(), nullable=False),
    sa.Column('nutrisi_id', sa.Uuid(), nullable=False),
    sa.Column('batas_min', sa.Float(), nullable=True),
    sa.Column('batas_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.ForeignKeyConstraint(['nutrisi_id'], ['nutrisi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='unique(fase_id, nutrisi_id) ditegakkan di migrasi'
    )
    op.create_index(op.f('ix_kebutuhan_nutrisi_fase_fase_id'), 'kebutuhan_nutrisi_fase', ['fase_id'], unique=False)
    op.create_index(op.f('ix_kebutuhan_nutrisi_fase_nutrisi_id'), 'kebutuhan_nutrisi_fase', ['nutrisi_id'], unique=False)
    op.create_table('siklus_kandang',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kandang_id', sa.Uuid(), nullable=False),
    sa.Column('jenis_ayam_id', sa.Uuid(), nullable=False),
    sa.Column('fase_id', sa.Uuid(), nullable=False),
    sa.Column('jumlah_ayam', sa.Integer(), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'SELESAI', name='statussiklus'), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.ForeignKeyConstraint(['jenis_ayam_id'], ['jenis_ayam.id'], ),
    sa.ForeignKeyConstraint(['kandang_id'], ['kandang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siklus_kandang_kandang_id'), 'siklus_kandang', ['kandang_id'], unique=False)
    op.create_table('standar_konsumsi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fase_id', sa.Uuid(), nullable=False),
    sa.Column('gram_per_ekor_per_hari', sa.Float(), nullable=False),
    sa.Column('frekuensi_makan', sa.Integer(), nullable=False),
    sa.Column('durasi_aduk', sa.Integer(), nullable=False),
    sa.Column('volume_air', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standar_konsumsi_fase_id'), 'standar_konsumsi', ['fase_id'], unique=True)
    op.create_table('wadah',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alat_id', sa.Uuid(), nullable=False),
    sa.Column('bahan_pakan_id', sa.Uuid(), nullable=True),
    sa.Column('nomor_wadah', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alat_id'], ['alat.id'], ),
    sa.ForeignKeyConstraint(['bahan_pakan_id'], ['bahan_pakan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wadah_alat_id'), 'wadah', ['alat_id'], unique=False)
    op.create_table('formulasi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('siklus_id', sa.Uuid(), nullable=False),
    sa.Column('dibuat_oleh_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('OTOMATIS', 'MANUAL', name='modeformulasi'), nullable=False),
    sa.Column('total_biaya_per_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'TIDAK_SEMPURNA', 'PERLU_DITINJAU', name='statusformulasi'), nullable=False),
    sa.Column('dibuat_pada', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dibuat_oleh_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['siklus_id'], ['siklus_kandang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulasi_siklus_id'), 'formulasi', ['siklus_id'], unique=False)
    op.create_table('perubahan_populasi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('siklus_id', sa.Uuid(), nullable=False),
    sa.Column('jenis', sa.Enum('MORTALITAS', 'PANEN', 'PENAMBAHAN', name='jenisperubahan'), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('catatan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['siklus_id'], ['siklus_kandang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perubahan_populasi_siklus_id'), 'perubahan_populasi', ['siklus_id'], unique=False)
    op.create_table('stok',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wadah_id', sa.Uuid(), nullable=False),
    sa.Column('jumlah_estimasi', sa.Float(), nullable=False),
    sa.Column('ambang_menipis', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['wadah_id'], ['wadah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_wadah_id'), 'stok', ['wadah_id'], unique=True)
    op.create_table('transaksi_stok',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wadah_id', sa.Uuid(), nullable=False),
    sa.Column('dilakukan_oleh_id', sa.Uuid(), nullable=False),
    sa.Column('jenis', sa.Enum('ISI_ULANG', 'KOREKSI_MANUAL', 'PENGELUARAN', name='jenistransaksi'), nullable=False),
    sa.Column('jumlah', sa.Float(), nullable=False),
    sa.Column('alasan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dibuat_pada', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dilakukan_oleh_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wadah_id'], ['wadah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_stok_wadah_id'), 'transaksi_stok', ['wadah_id'], unique=False)
    op.create_table('formulasi_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formulasi_id', sa.Uuid(), nullable=False),
    sa.Column('bahan_pakan_id', sa.Uuid(), nullable=False),
    sa.Column('proporsi', sa.Float(), nullable=False),
    sa.Column('berat_per_sesi', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bahan_pakan_id'], ['bahan_pakan.id'], ),
    sa.ForeignKeyConstraint(['formulasi_id'], ['formulasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulasi_item_formulasi_id'), 'formulasi_item', ['formulasi_id'], unique=False)
    op.create_table('formulasi_nutrisi_hasil',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formulasi_id', sa.Uuid(), nullable=False),
    sa.Column('nutrisi_id', sa.Uuid(), nullable=False),
    sa.Column('nilai_hasil', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('KURANG', 'SESUAI', 'BERLEBIH', name='statusnutrisi'), nullable=False),
    sa.ForeignKeyConstraint(['formulasi_id'], ['formulasi.id'], ),
    sa.ForeignKeyConstraint(['nutrisi_id'], ['nutrisi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulasi_nutrisi_hasil_formulasi_id'), 'formulasi_nutrisi_hasil', ['formulasi_id'], unique=False)
    op.create_table('perintah',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alat_id', sa.Uuid(), nullable=False),
    sa.Column('dibuat_oleh_id', sa.Uuid(), nullable=False),
    sa.Column('formulasi_id', sa.Uuid(), nullable=True),
    sa.Column('tipe', sa.Enum('BERI_MAKAN', 'TEST', 'STOP_DARURAT', 'RESET_ERROR', name='tipeperintah'), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DIAMBIL', 'BERJALAN', 'SUKSES', 'GAGAL', 'TIMEOUT', name='statusperintah'), nullable=False),
    sa.Column('dibuat_pada', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alat_id'], ['alat.id'], ),
    sa.ForeignKeyConstraint(['dibuat_oleh_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['formulasi_id'], ['formulasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perintah_alat_id'), 'perintah', ['alat_id'], unique=False)
    op.create_index(op.f('ix_perintah_command_id'), 'perintah', ['command_id'], unique=True)
    op.create_table('log_eksekusi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('perintah_id', sa.Uuid(), nullable=False),
    sa.Column('id_eksekusi_unik', sa.Uuid(), nullable=False),
    sa.Column('berat_aktual', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUKSES', 'GAGAL', 'SKIPPED_STOCK', name='statuseksekusi'), nullable=False),
    sa.Column('dilaporkan_pada', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perintah_id'], ['perintah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_eksekusi_id_eksekusi_unik'), 'log_eksekusi', ['id_eksekusi_unik'], unique=True)
    op.create_index(op.f('ix_log_eksekusi_perintah_id'), 'log_eksekusi', ['perintah_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_eksekusi_perintah_id'), table_name='log_eksekusi')
    op.drop_index(op.f('ix_log_eksekusi_id_eksekusi_unik'), table_name='log_eksekusi')
    op.drop_table('log_eksekusi')
    op.drop_index(op.f('ix_perintah_command_id'), table_name='perintah')
    op.drop_index(op.f('ix_perintah_alat_id'), table_name='perintah')
    op.drop_table('perintah')
    op.drop_index(op.f('ix_formulasi_nutrisi_hasil_formulasi_id'), table_name='formulasi_nutrisi_hasil')
    op.drop_table('formulasi_nutrisi_hasil')
    op.drop_index(op.f('ix_formulasi_item_formulasi_id'), table_name='formulasi_item')
    op.drop_table('formulasi_item')
    op.drop_index(op.f('ix_transaksi_stok_wadah_id'), table_name='transaksi_stok')
    op.drop_table('transaksi_stok')
    op.drop_index(op.f('ix_stok_wadah_id'), table_name='stok')
    op.drop_table('stok')
    op.drop_index(op.f('ix_perubahan_populasi_siklus_id'), table_name='perubahan_populasi')
    op.drop_table('perubahan_populasi')
    op.drop_index(op.f('ix_formulasi_siklus_id'), table_name='formulasi')
    op.drop_table('formulasi')
    op.drop_index(op.f('ix_wadah_alat_id'), table_name='wadah')
    op.drop_table('wadah')
    op.drop_index(op.f('ix_standar_konsumsi_fase_id'), table_name='standar_konsumsi')
    op.drop_table('standar_konsumsi')
    op.drop_index(op.f('ix_siklus_kandang_kandang_id'), table_name='siklus_kandang')
    op.drop_table('siklus_kandang')
    op.drop_index(op.f('ix_kebutuhan_nutrisi_fase_nutrisi_id'), table_name='kebutuhan_nutrisi_fase')
    op.drop_index(op.f('ix_kebutuhan_nutrisi_fase_fase_id'), table_name='kebutuhan_nutrisi_fase')
    op.drop_table('kebutuhan_nutrisi_fase')
    op.drop_index(op.f('ix_penugasan_kandang_user_id'), table_name='penugasan_kandang')
    op.drop_index(op.f('ix_penugasan_kandang_kandang_id'), table_name='penugasan_kandang')
    op.drop_table('penugasan_kandang')
    op.drop_index(op.f('ix_kandungan_nutrisi_bahan_nutrisi_id'), table_name='kandungan_nutrisi_bahan')
    op.drop_index(op.f('ix_kandungan_nutrisi_bahan_bahan_pakan_id'), table_name='kandungan_nutrisi_bahan')
    op.drop_table('kandungan_nutrisi_bahan')
    op.drop_index(op.f('ix_fase_jenis_ayam_id'), table_name='fase')
    op.drop_table('fase')
    op.drop_index(op.f('ix_alat_kandang_id'), table_name='alat')
    op.drop_index(op.f('ix_alat_device_token'), table_name='alat')
    op.drop_table('alat')
    op.drop_index(op.f('ix_nutrisi_pemilik_id'), table_name='nutrisi')
    op.drop_table('nutrisi')
    op.drop_index(op.f('ix_notifikasi_user_id'), table_name='notifikasi')
    op.drop_table('notifikasi')
    op.drop_index(op.f('ix_kandang_pemilik_id'), table_name='kandang')
    op.drop_table('kandang')
    op.drop_index(op.f('ix_jenis_ayam_pemilik_id'), table_name='jenis_ayam')
    op.drop_table('jenis_ayam')
    op.drop_index(op.f('ix_bahan_pakan_pemilik_id'), table_name='bahan_pakan')
    op.drop_table('bahan_pakan')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
